<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-06T05:02:25Z" name="Default suite" finished-at="2020-06-06T05:02:25Z" duration-ms="80">
    <groups>
    </groups>
    <test started-at="2020-06-06T05:02:25Z" name="Default test" finished-at="2020-06-06T05:02:25Z" duration-ms="80">
      <class name="TestCalculator">
        <test-method is-config="true" signature="init()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="init" finished-at="2020-06-06T05:02:25Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="addThreeNUmberWithDelimeterReturnSum()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="addThreeNUmberWithDelimeterReturnSum" finished-at="2020-06-06T05:02:25Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addThreeNUmberWithDelimeterReturnSum -->
        <test-method signature="emptyStringReturnZero()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="emptyStringReturnZero" finished-at="2020-06-06T05:02:25Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyStringReturnZero -->
        <test-method signature="negativeException()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="negativeException" finished-at="2020-06-06T05:02:25Z" duration-ms="2" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestCalculator.negativeException()[pri:0, instance:TestCalculator@770c2e6b] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestCalculator.negativeException()[pri:0, instance:TestCalculator@770c2e6b] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeException -->
        <test-method signature="singleValueReply()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="singleValueReply" finished-at="2020-06-06T05:02:25Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleValueReply -->
        <test-method signature="twoNumbersCommaDelimeterReturnSum()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="twoNumbersCommaDelimeterReturnSum" finished-at="2020-06-06T05:02:25Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumbersCommaDelimeterReturnSum -->
        <test-method signature="twonumbersLinechnageDelimeterReturnsum()[pri:0, instance:TestCalculator@770c2e6b]" started-at="2020-06-06T05:02:25Z" name="twonumbersLinechnageDelimeterReturnsum" finished-at="2020-06-06T05:02:25Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twonumbersLinechnageDelimeterReturnsum -->
      </class> <!-- TestCalculator -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
